### ISSUE TITLE
OsError from h5py when loading in a solution database

### ISSUE THREAD

**Issue by mattirish** [NREL/h5plexos#12]
I am using h5py 2.9.0. With some PLEXOS solutions, but not others (even when they were created from the same set of HPC PLEXOS runs at the same time), when I try to open an h5, I get the following:

```python
>PLEXOSSolution(<string or path object referring to h5plexos HDF5>)

OSError: Unable to read attribute (no appropriate function for conversion path)
```

This may be related to https://github.com/h5py/h5py/issues/719. Finding out more!

**Comment by GordStephen** [comment]
@MartySchwarz had this issue recently - IIRC the best solution was just to upgrade to h5py 2.10. We tried getting H5PLEXOS.jl to use an older HDF5 library but that didn't seem to help.

**Comment by mattirish** [comment]
Thank you both! I updated to >2.10 and that fixed it.
